### PR TITLE
pc/vp - create new branch from Victor's old branch with only the Pending Request Table

### LINKED ISSUE #85: Professor can see list of requests and details of the request specifically for them

### PR DESCRIPTION
**Pull request by vprchlik**
Storybook: https://6734fdad790fe98dc6bf77f1-vcwjkyaeug.chromatic.com/?path=/docs/components-pendingrequeststable--docs

Added basic functionality for the frontend portion of FEATURE #17. There is no backend implementation yet, but the Pending Requests Table is visible and properly shows the list of pending requests and their details. Closes #85.

image

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
I'll approve this, but I'd observe that it doesn't seem like it very closely matches the actual needs of the end user.

There isn't enough information displayed in this table for either the student or the professor to make any sense of the requests here or take any action.  Where are the details such as:
* request type
* request details
* due date

A minimum viable product needs to be "viable" and this ... isn't?

**Comment by pconrad** [comment]
I'm assigning only 5 points because this one would surely have to be revisited and considerably changed to be useful.

We'd need more data elements in the fixtures, and either more data in the table, or we'd need each row to links to a separate show page that shows all of the details for a single request.

**Comment by pconrad** [comment]
Oh, also: there's no team code review.  So Victor, why did you add `Ready For Staff` in the first place? Removing it and the points until you get a code review.

**Review by ELEXG — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM, though a bit thin on details that the end users are likely to need.

**Pull request merged**
