### PR TITLE
Delete all files non-related to Request Feature

### LINKED ISSUE #19: Deleting non-Recommendation Request files

### PR DESCRIPTION
**Pull request by SexyCarrots**
Closes #19 
Dokku Deployment: https://xinghan-dev.dokku-06.cs.ucsb.edu/
This PR removes all frontend and backend features and corresponding test files that are non-related to the Request feature for group projects because they are not part of our specifications for this project.

### CODE REVIEW

**Review by skanda-vasishta — APPROVED** [review]
LGTM

**Comment by SexyCarrots** [comment]
# Ready for review

**Comment by SexyCarrots** [comment]
Hi Profesor @pconrad . I just finished all the changes requested. It should be ready for code review. No rush and many thanks

**Comment by SexyCarrots** [comment]
@pconrad 
Hi professor.
PR Dokku Deployment: https://xinghan-dev.dokku-06.cs.ucsb.edu/
Ready to go.

**Comment by SexyCarrots** [comment]
@pconrad 
Hi professor.
PR Dokku Deployment: https://xinghan-dev.dokku-06.cs.ucsb.edu/
Ready to go.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
