### PR TITLE
eg - professor tab on navbar, three placeholders pages for pending requests, completed requests, and statistics pages

### LINKED ISSUE #89: Create professor tab on navbar
part of issue #73 
Adds a professor tab to the navbar. Only users with the professor role can see it.

### LINKED ISSUE #90: Create placeholder page for completed requests
part of issue #73

### LINKED ISSUE #91: Create placeholder page for statistics
part of issue https://github.com/ucsb-cs156-f24/proj-rec-f24-06/issues/73

### LINKED ISSUE #95: Create placeholder page for pending requests

### PR DESCRIPTION
**Pull request by ELEXG**
Closes #89, Closes #90, Closes #91, Closes #95

Dokku deployment: https://proj-rec-elexg.dokku-06.cs.ucsb.edu/
Storybook: https://6734fdad790fe98dc6bf77f1-vijmfyxinv.chromatic.com/?path=/docs/pages-professor-professorcompletedrequestspage--docs

Creates a new tab for professor users. Professor tab links to these urls:
/requests/pending, 
/requests/completed
/requests/statistics

This PR also creates three placeholder pages, one for each link.

Also adds tests for the placeholder pages. Right now it just makes sure that the pages render with the correct title

Additionally, there is a small update to currentUsersFixtures which adds professor role to ensure full coverage for tests.

Frontend changes: 
Professor Tab. Toggle professor role in the admin menu and you will see this professor tab.
Screenshot 2024-11-25 115800

Pending Requests Placeholder 
Screenshot 2024-11-29 153150

Completed Requests Placeholder
Screenshot 2024-11-25 120314

Statistics Placeholder
Screenshot 2024-11-25 120322

### CODE REVIEW

**Review by SexyCarrots — DISMISSED** [review]
# LGTM

**Review by pconrad — DISMISSED** [review]
LGTM... will test on dokku

**Comment by ELEXG** [comment]
> LGTM... will test on dokku

Deployed: https://proj-rec-elexg.dokku-06.cs.ucsb.edu/

**Review by SexyCarrots — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
It's a little inconsistent to add three menu items but create placeholders for only two of them. 

Please either add the missing placeholder, or remove the menu item that leads to a blank page.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
