### PR TITLE
CL: Add RequestType table (db migration, entity, repository)

### LINKED ISSUE #22: Add RequestType table (db migration, entity, repository)
Creates the starting point for the RequestType class. This Issue should create/edit the following files:
- RequestType.java (entity)
- RequestType.json (db migration)
- RequestTypeRepository.java
- RequestTypeApplicationRunner.java
- RequestTypeService.java
- RequestTypeServiceTests.java

This issue is a related task to FEATURE #10 and will be used to fully integrate RequestType into our application in the future.

### PR DESCRIPTION
**Pull request by chriswlai**
Dokku deployment: https://proj-rec.dokku-06.cs.ucsb.edu/

This PR creates the RequestType class entity, migration JSON file, repository file, service files, and tests. The service method iterates through the list of strings; for each one look in the RequestTypes table and see if it is there. If not, then add it to the RequestType table.

These tasks create a starting point to eventually fully integrate RequestType into our application.

Closes #22 

Note:
I'm curious is the pending Chromatic checks are related to this response.

https://ucsb-cs156-f24.slack.com/archives/C07P9T925KL/p1732070844878609?thread_ts=1732067873.577169&cid=C07P9T925KL

### CODE REVIEW

**Comment by chriswlai** [comment]
I'm curious is the pending Chromatic checks is related to this response.

https://ucsb-cs156-f24.slack.com/archives/C07P9T925KL/p1732070844878609?thread_ts=1732067873.577169&cid=C07P9T925KL

**Review by skanda-vasishta — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
Awarding 20 because this not only creates the database + controller, but also includes the code to initialize the table with some initial values.

**Pull request merged**
